### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by notgull** [lasarobotics/FTCVision#101]
Hello there, do you mind expanding on the documentation a little, i.e. adding examples to your classes, or giving example cases on how this would be used? I would be very appeciative of this.

**Comment by smo-key** [comment]
@tf2hoovy Take a look at the files in https://github.com/lasarobotics/FTCVision/tree/master/ftc-robotcontroller/src/main/java/com/qualcomm/ftcrobotcontroller/opmodes. These files give some explanation on the most commonly used (i.e. most high-level) methods available in the library.

Are you writing a ManualVisionOpMode? If so, you have the power of the entire OpenCV library available to you (the `Mat` objects returned here are native OpenCV image matrices). In this case, the documentation at http://docs.opencv.org/3.1.0 supplements our own at http://ftcvision.lasarobotics.org.

Otherwise, what files or categories would you like documented? What do you/your team need to accomplish? FTCVision has many functions designed to make OpenCV easy to use and set up. While we are unable to provide samples for _every section_, we can certainly help point you in the right direction and/or provide an example or so right here in this issue.

Let us know how we can help.
Arthur (smo-key)

**Comment by jrasor** [comment]
Adding camera test, a suggestion for the installation tutorial right on the Lasarobotics Github page. I think it should say, "Add the whole ftc-cameratest folder, not just the files within it, into the root of your project." instead of “copying all files from  ftc-cameratest  into the root of your project.” Sync:  no gripes. Works.

**Comment by ehsanmasdar** [comment]
@jrasor Good point! Fixed.
