### ISSUE TITLE
While-loops freeze the program?

### ISSUE THREAD

**Issue by DanielArnett** [lasarobotics/FTCVision#54]
When I switch from extending LinearOpMode to VisionOpMode my control loops for driving the robot get stuck. Is there a way I can call the vision processing from a program in LinearOpMode or is there a way I can control the robot from VisionOpMode?

Thank you!

**Comment by smo-key** [comment]
Hi @DanielArnett,

We are currently working on a `LinearVisionOpMode` extension that allows you to extend the linear OpMode class and use vision without having it block your program's execution. Since a typical set of vision code takes about 20-200ms to analyze a frame and return data and the `LinearOpMode` class expects your loop to complete in about 10ms, using vision will block a linear-style loop.

**We strongly recommend migrating your code to a regular `OpMode`-like syntax** - make sure your class extends `VisionOpMode` and move everything within your `while()` loop into the `loop()` function and everything before this into an `init()` function. _You can then access vision in your `loop()` method via objects such as `beaconColor` and `fps`._ We have a few examples in `ftc-robotcontroller/src/main/java/com/qualcomm/ftcrobotcontroller/opmodes` for you to look at - `BasicVisionSample` would be where to start.

**Comment by DanielArnett** [comment]
Thank you for the feedback, we've made great progress thanks to your help.
If anyone encounters a similar issue, I highly recommend using a State
Machine structure like the one described in this beginner tutorial.
https://youtu.be/cPgJ8bbBj_o

**Comment by smo-key** [comment]
@DanielArnett We just implemented linear opmode support on the `dev` branch!

The `LinearVisionOpMode` adds vision support to a `LinearOpMode`. All you have to do is extend `LinearVisionOpMode`, add a `waitForVisionStart()` at the beginning of your `runOpMode()` as well any any vision-related initialization instructions, and you're done! See the `LinearVisionSample` for more details and functionality.

Glad to hear the state machine structure worked out for your team. For many others, a linear op mode is the simplest route.

Closes #54.
