### ISSUE TITLE
SDK Incompatibility

### ISSUE THREAD

**Issue by buggy213** [lasarobotics/FTCVision#93]
After installing using Git submodule into the latest FTC SDK, there were multiple compilation errors, After removing the annotations in Eclipse.java IIRC (they shouldn't be mandatory, they are marker annotations), the project compiled. I pushed it onto the phone, but as soon as I chose the sample opmode (all of them had the same issue) and pressed INIT, the RobotController crashed. The error logs are nearly indecipherable, saying something about internal issues (coming from robotcore).

**Comment by smo-key** [comment]
Hi @buggy213,

Thanks for your issue! A few things:
1. Are you using Android Studio 2.1 or newer? (Eclipse is NOT supported - and shouldn't be supported by the FIRST app).
2. If so, can you send me a copy of the `Eclipse.java` file where you removed the annotations and where it is located?
3. Also, can you paste or send the error logs, even the unreadable parts (_especially_ internal issues)? They will help make the debugging process much simpler.

**Comment by buggy213** [comment]
1.Yes
2.Yes [Link](https://drive.google.com/file/d/0B4VhPo0mRKLYNWZMdlJkVDNQVnM/view?usp=sharing)
3.Yes (adding this later)

**Comment by smo-key** [comment]
@buggy213 Thanks for the copy of `Eclipse.java`. That issue is now fixed and a patch pushed to `dev`.

Reply once you have the error logs - I am currently unable to test anything involving the driver controller on my end.

A few things to make sure you are doing, but otherwise it is likely an expected error as part of updating between versions of the FIRST app:
- You have the latest, non-beta (stable) version of the driver controller and ftc_app. Both should report Robot Wifi Protocol Version "v11" in their about pages.
- You do not have both the robot controller _and_ driver station on the same phone. This has been known to cause issues in previous releases of the FIRST app.
- Otherwise, your environment should be good. Just send the logs when you have the chance.

Arthur

**Comment by tommy-mor** [comment]
hello, I am experiencing the EXACT same thing as OP and, want this fixed.
I had to fix annotation errors in ellipse.java, (because I did not pull from the dev branch).
The app crashes as soon as I select it and press init.
This is the logcat of the crash (sorry that its 7000 lines)
https://gist.github.com/tommy-mor/540d440c242f6e8bdcdab01f66fc8d5
after grepping through it a bit, I found a relevant part

`W/System.err( 7843): java.lang.UnsatisfiedLinkError: Couldn't load opencv_java3 from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.qualcomm.ftcrobotcontroller-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.qualcomm.ftcrobotcontroller-2, /vendor/lib, /system/lib]]]: findLibrary returned null
W/System.err( 7843):    at com.qualcomm.robotcore.eventloop.opmode.OpModeManagerImpl$2.run(OpModeManagerImpl.java:570)
W/System.err( 7843):    at com.qualcomm.robotcore.eventloop.opmode.OpModeManagerImpl.detectStuck(OpModeManagerImpl.java:481)
W/System.err( 7843):    at com.qualcomm.robotcore.eventloop.opmode.OpModeManagerImpl.callActiveOpModeInit(OpModeManagerImpl.java:568)
W/System.err( 7843):    at com.qualcomm.robotcore.eventloop.opmode.OpModeManagerImpl.runActiveOpMode(OpModeManagerImpl.java:362)
W/System.err( 7843):    at com.qualcomm.ftccommon.FtcEventLoop.loop(FtcEventLoop.java:218)
W/System.err( 7843):    at com.qualcomm.robotcore.eventloop.EventLoopManager$EventLoopRunnable$1.run(EventLoopManager.java:292)
W/System.err( 7843):    at com.qualcomm.robotcore.util.ThreadPool.logThreadLifeCycle(ThreadPool.java:513)
W/System.err( 7843):    at com.qualcomm.robotcore.eventloop.EventLoopManager$EventLoopRunnable.run(EventLoopManager.java:246`

**Comment by ehsanmasdar** [comment]
@tommy-mor Do you have the OpenCV Manager app installed on your Android device?

**Comment by tommy-mor** [comment]
Yes, and I tried reinstalling it.

**Comment by smo-key** [comment]
Hi @tommy-mor,

Thank you for the report! The lines you found are exactly the lines causing the problem. As it states, the OpenCV library is missing from the expected location.

I will be able to diagnose the problem further this weekend, but first: what phone are you using and can you check its architecture (e.g. armeabi-v7a, x86_64, etc.)? It is possible that the OpenCV library was not compiled for your ABI (this can be fixed but only if necessary as it adds a few steps to the setup routine).

**Comment by buggy213** [comment]
We were using the ZTE Speed phone which uses the ARMv8 architecture

**Comment by smo-key** [comment]
Thanks. I'll look into it ASAP.

**Comment by tommy-mor** [comment]
We are also using the zte speed.

**Comment by Zero2848** [comment]
I think I found the issue, but dont exactly now why its causing an error. It seems to be in the telemetry in line 257 in https://github.com/lasarobotics/FTCVision/blob/master/ftc-visionlib/src/main/java/org/lasarobotics/vision/opmode/VisionOpModeCore.java#L257

**Comment by Zero2848** [comment]
Commenting the telemetry solved the crashing issue for me.

**Comment by buggy213** [comment]
Huh. It worked. Thanks mate!

**Comment by qwertychouskie** [comment]
Related PRs merged, can be closed.
